### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by arnecornillie-gantner** [FusionAuth/fusionauth-load-tests#4]
Hi all,

I would like to load test our fusionauth setup. This library contains everything I need!
Only one small issue, I'm unable to build the project...

Does anyone know how to fix this?
![image](https://user-images.githubusercontent.com/84460326/160650969-b1d5621a-ab56-4f71-80ec-74b8399e8e4a.png)

I installed savant as described.

Thanks in advance!

**Comment by mooreds** [comment]
@arnecornillie-gantner looks like it is set up for an internal library version. Can you try changing

`fusionauthVersion = "1.35.1-{integration}"`

in `build.savant` to

`fusionauthVersion = "1.35.0"`

and see if the project builds?

**Comment by arnecornillie-gantner** [comment]
Thanks @mooreds 

I changed the version to "1.35.0", the error changed in another one:
![image](https://user-images.githubusercontent.com/84460326/160777188-31c8e12e-77f1-4d91-a190-e034eba78cc7.png)

Should I install some other tools before building the load tests?

Thanks in advance!

**Comment by mooreds** [comment]
You need to make sure JDK 17 is installed and you have a line in the plugins file which points to it. It would look something like:

```
17=/path/to/jdk17
```

**Comment by johnjeffers** [comment]
The readme has been extensively updated, so hopefully addresses these kinds of questions now.
